# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AutoPull < Formula
  desc "Automatically pull git repositories on a schedule (macOS menu bar app)"
  homepage "https://github.com/adreasnow/auto-pull"
  version "2026.3.1"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/adreasnow/auto-pull/releases/download/v2026.3.1/auto-pull_darwin_amd64.zip"
    sha256 "d21e896d5d92c359db1869cbbf8392ff3d36c5ffce127a9ebf0235d3c9730aa3"

    define_method(:install) do
      app_contents = prefix/"Auto Pull.app"/"Contents"
      (app_contents/"MacOS").install "autopull"
      (app_contents/"Resources").install "icon.icns", "cloud.png", "sun.png", "warning.png"
      app_contents.install "Info.plist"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/adreasnow/auto-pull/releases/download/v2026.3.1/auto-pull_darwin_arm64.zip"
    sha256 "ae18b6758d1ccece8267c2fcc6e79cb43f3433c0dd7a5d9d190bc400b37ac8e8"

    define_method(:install) do
      app_contents = prefix/"Auto Pull.app"/"Contents"
      (app_contents/"MacOS").install "autopull"
      (app_contents/"Resources").install "icon.icns", "cloud.png", "sun.png", "warning.png"
      app_contents.install "Info.plist"
    end
  end
end
