# This file was generated by GoReleaser. DO NOT EDIT.
cask "auto-pull" do
  app "Auto Pull.app"

  name "auto-pull"
  desc "Automatically pull git repositories on a schedule (macOS menu bar app)"
  homepage "https://github.com/adreasnow/auto-pull"
  version "2026.3.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "Auto Pull.app/Contents/MacOS/autopull"

  on_macos do
    on_intel do
      url "https://github.com/adreasnow/auto-pull/releases/download/v#{version}/auto-pull_darwin_amd64.zip"
      sha256 "7534dfe558b5cbc35533a8fe9a5d53790961c0489ff0e7b46ca78879d27812f4"
    end
    on_arm do
      url "https://github.com/adreasnow/auto-pull/releases/download/v#{version}/auto-pull_darwin_arm64.zip"
      sha256 "8a4a00b04e63abe2a561d36e435003baec68d8ed977ea1105679e9100b1559fc"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/Auto Pull.app"]
  end

  uninstall quit: [
      "com.github.adreasnow.auto-pull",
    ]

  zap trash: [
      "~/.config/auto-pull",
      "~/Library/Logs/com.github.adreasnow.auto-pull",
    ]

end
