# This file was generated by GoReleaser. DO NOT EDIT.
cask "auto-pull" do
  app "Auto Pull.app"

  version "2026.7.4"

  on_macos do
    on_intel do
      sha256 "aa4732909a8e34f2434b76b22d25e4c5a8667517853748c1486788973ac82b21"
      url "https://github.com/adreasnow/auto-pull/releases/download/v#{version}/auto-pull_darwin_amd64.zip"
    end
    on_arm do
      sha256 "e4df7a156fd78fa17432fb709466dcb9549ef7d0467e5767876850fa2c07db2e"
      url "https://github.com/adreasnow/auto-pull/releases/download/v#{version}/auto-pull_darwin_arm64.zip"
    end
  end

  name "auto-pull"
  desc "Automatically pull git repositories on a schedule (macOS menu bar app)"
  homepage "https://github.com/adreasnow/auto-pull"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "Auto Pull.app/Contents/MacOS/autopull"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/Auto Pull.app"]
  end

  uninstall quit: [
      "com.github.adreasnow.auto-pull",
    ]

  zap trash: [
      "~/.config/auto-pull",
      "~/Library/Logs/com.github.adreasnow.auto-pull",
    ]

end
