# This file was generated by GoReleaser. DO NOT EDIT.
cask "keychron-launcher" do
  app "Keychron Launcher.app"

  name "keychron-launcher"
  desc "Keychron Launcher electron app"
  homepage "https://github.com/adreasnow/keychron-launcher"
  version "2026.3.8"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "keychron-launcher"

  on_macos do
    on_arm do
      url "https://github.com/adreasnow/keychron-launcher/releases/download/v#{version}/Keychron-Launcher_darwin_arm64.zip"
      sha256 "726db286c4ad178dcfacd3c9ce2170f681506564c87903747888a85dc541ad34"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/Keychron Launcher.app"]
  end

  uninstall quit: [
      "com.electron.keychron-launcher",
    ]

  zap trash: [
      "~/Library/Application Support/Keychron Launcher",
      "~/Library/Caches/Keychron Launcher",
      "~/Library/Preferences/com.electron.keychron-launcher.plist",
    ]

end
