# This file was generated by GoReleaser. DO NOT EDIT.
cask "keychron-launcher" do
  app "Keychron Launcher.app"

  name "keychron-launcher"
  desc "Keychron Launcher electron app"
  homepage "https://github.com/adreasnow/keychron-launcher"
  version "2026.3.5"

  livecheck do
    skip "Auto-generated on release."
  end

  on_macos do
    on_arm do
      url "https://github.com/adreasnow/keychron-launcher/releases/download/v#{version}/Keychron-Launcher.app.zip"
      sha256 "a933eebf6f764d9f2f248d4b276f6fcc0e09791b00909b1f2bca34b6830960b7"
      binary "Keychron-Launcher.app.zip", target: "keychron-launcher"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/Keychron Launcher.app"]
  end

  uninstall quit: [
      "com.electron.keychron-launcher",
    ]

  zap trash: [
      "~/Library/Application Support/Keychron Launcher",
      "~/Library/Caches/Keychron Launcher",
      "~/Library/Preferences/com.electron.keychron-launcher.plist",
    ]

end
