# This file was generated by GoReleaser. DO NOT EDIT.
cask "keys" do
  name "keys"
  desc "Lightweight Go wrapper around your OS keychain to act as a simple CLI tool for managing secrets."
  homepage "https://github.com/adreasnow/keys"
  version "2026.3.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "keys"
  bash_completion "completions/keys.bash"
  zsh_completion "completions/keys.zsh"
  fish_completion "completions/keys.fish"

  on_macos do
    on_intel do
      url "https://github.com/adreasnow/keys/releases/download/v#{version}/keys_darwin_amd64.tar.gz"
      sha256 "c11bce2898324939b76fa13197c7946ea323ea5f061e3025a6ced6cf020d1c17"
    end
    on_arm do
      url "https://github.com/adreasnow/keys/releases/download/v#{version}/keys_darwin_arm64.tar.gz"
      sha256 "9e5cf7eefe35a0b5586087cd9084c19d9d0eacab928c1ac3e7f71d4d9d088870"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/adreasnow/keys/releases/download/v#{version}/keys_linux_amd64.tar.gz"
      sha256 "152ba7fcf95a15591c5fa5120c5781893bd88502c100fbb6edfd25f064b1c2db"
    end
    on_arm do
      url "https://github.com/adreasnow/keys/releases/download/v#{version}/keys_linux_arm64.tar.gz"
      sha256 "8225a3efd803e32ce00a410cc159a30b6e9fb6927056fdcc835772e5d2a4b46d"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/keys"]
    end
  end

  # No zap stanza required
end
