# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Keys < Formula
  desc "Lightweight Go wrapper around your OS keychain to act as a simple CLI tool for managing secrets."
  homepage "https://github.com/adreasnow/keys"
  version "2026.6.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/adreasnow/keys/releases/download/v2026.6.4/keys_darwin_amd64.tar.gz"
      sha256 "d7e096ef9fcfc7ff0c5ecb1a487c1356290b1af9ec03108678732b7650d5f628"

      define_method(:install) do
        bin.install "keys"
        bash_completion.install "completions/keys.bash" => "keys"
        zsh_completion.install "completions/keys.zsh" => "_keys"
        fish_completion.install "completions/keys.fish" => "keys.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/adreasnow/keys/releases/download/v2026.6.4/keys_darwin_arm64.tar.gz"
      sha256 "558d57f146ec0f61a941248d262c0993147367294eaf2e3eb4d3d6ea78ad2414"

      define_method(:install) do
        bin.install "keys"
        bash_completion.install "completions/keys.bash" => "keys"
        zsh_completion.install "completions/keys.zsh" => "_keys"
        fish_completion.install "completions/keys.fish" => "keys.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/adreasnow/keys/releases/download/v2026.6.4/keys_linux_amd64.tar.gz"
      sha256 "e4ede9011e6ecd2c0a2ede12c2e809783fc5ee4dc5272460c2bc480d66855f80"
      define_method(:install) do
        bin.install "keys"
        bash_completion.install "completions/keys.bash" => "keys"
        zsh_completion.install "completions/keys.zsh" => "_keys"
        fish_completion.install "completions/keys.fish" => "keys.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/adreasnow/keys/releases/download/v2026.6.4/keys_linux_arm64.tar.gz"
      sha256 "72416fac2321b5f694377d555542b8a9427f2f2556878077d51384b07217e271"
      define_method(:install) do
        bin.install "keys"
        bash_completion.install "completions/keys.bash" => "keys"
        zsh_completion.install "completions/keys.zsh" => "_keys"
        fish_completion.install "completions/keys.fish" => "keys.fish"
      end
    end
  end
end
